version: 2.1

jobs:
  run_tests:
    steps:
      - checkout
      - run:
        name: node/install-packages
        command: npm install --save
      - run:
        name: node/test
        command: npm run test

workflows:
  build_test:
    jobs:
      - run_tests
